### ISSUE TITLE
Inherit material properties of inserted block

### ISSUE THREAD

**Issue by davids-tusker** [MysticMods/Blockcraftery#55]
Love the Mod Mr Squid :)

As a suggestion - is it possible for the various Blockcraftery items to take on the properties of the material inserted? Presently when I place in a Reinforced Stone (blast proof block) and the blockcraftery block then struck by lightning, effected by TNT or Creeper explosions it's either destroyed or broke into an entity. My reinforced super bunker is now full of swiss cheese holes due to lots of thunderstorms on my server ;)

**Comment by EpicSquid** [comment]
Use the reinforced blockcraftery frames. They are designed to stop all explosions and fire so that any block can be used for decoration without risk.

**Comment by davids-tusker** [comment]
Ah derp!

thanks, sorry for the noise!
